### ISSUE TITLE
Really expose ffmpeg output to Stdout/Stderr?

### ISSUE THREAD

**Issue by gonutz** [jtguibas/cinema#4]
I find it questionable to write to stdout from a library, maybe the API interface should be changed to make the ffmpeg output available explicitly.

**Comment by jtguibas** [comment]
Could you elaborate on this? I am a bit confused on what you are trying to say. Are you referring to how I print the entire stdout every-time `v.Render()` is called?

If that's the case, I definitely see your point. However, I want to make sure that errors from FFMPEG can easily be figured out for the user. 

In the future, I actually am thinking about implementing a progress bar that can show how long the rendering will take (don't know if this is possible) instead of the entire FFMPEG console output.

**Comment by gonutz** [comment]
I think you should be able to get all output programatically without needing to overwrite the global Stdout and Stderr. Things like logging to stdout should generally not happen inside libraries but rather on the caller site or at least via an explicit parameter to specify where and what to log, if we really need to see what happens inside a library.

In this case I know why you did this, ffmpeg uses stdout to report progress and parsing it is not really a viable option as you would always have to know the exact specific output format which can change between any two versions. This means you would have to know for every version the format and put that in the library etc. Overall a bad option.

What I have in mind is maybe an extra parameter or two for redirection of stdout and stderr. Then maybe the caller could insert os.Stdout and os.Stdin there themselves. Or maybe they pass nil and we use stdout by default. Then again, maybe we use a nil writer by default instead. This has to be decided but I think just forwarding everything to stdout without the user being able to change it needs to be avoided. The best solution here is not clear to me either.

Another idea is to, instead of Render running the exec.Command, return the Command and let the user run it. This has the negative effect of making this operation a little more tedious but the positive effect of having control over where the output goes. Having the Command object gives the user all the control over sync/async execution and stdout/stderr.
If this were the solution we decided on, the CommandLine and Render functions could be merged into one

    func Command() *exec.Cmd

or something similar.

Again, I do not know best answer to this issue, yet. What I am sure about, though, is that not having the user in control of the stdout/stderr output is a drawback that should be addressed.

**Comment by jtguibas** [comment]
Thanks for the clarification! I see what you're saying now. Out of the two options you proposed, I'm currently leaning towards the `func Command() *exec.Cmd` one. 

One thing I would like for the user to understand is that this library creates a single FFMPEG command to edit their video and that they can use this command even outside of Go. Currently, by using `v.Render()`, it obfuscates this fact. It is not clear what is happening behind the scenes.

**Comment by denysvitali** [comment]
Please check my PR. It should fix this issue :D
