### ISSUE TITLE
Duration always returns the length of the input video

### ISSUE THREAD

**Issue by gonutz** [jtguibas/cinema#5]
Calling Trim will not change the result of the Duration function. This might be misleading but is probably what we want. In that case, we should update the doc comment to state that Duration is always the duration of the input video.

**Comment by jtguibas** [comment]
Yes, I think you're right here. Duration should definitely change according to Trim. Also, Trim right now is always called relative to the original video file, but this is very unintuitive IMO and should be changed.

**Comment by gonutz** [comment]
As I said, Duration returning the original video's duration might be what we want. I imaging both information to be useful actually, the current trim section as well as the original duration so maybe another function OriginalDuration could be useful? If that was the case, original versions of the other properties could also be useful. But then I think, there is no concrete use-case so why implement it right now? If people wanted this extra functionality there would be an issue here. Probably it is better not to complicate the API but rather state what it does and its side effects on other functions as clearly as possible. Also the original values can be copied by the user before altering the Video object.
